### ISSUE TITLE
DerivativesDatasink corrupting files and bus error

### ISSUE THREAD

**Issue by fmorfini** [nipreps/niworkflows#639] opened 2021-05-19 17:49 UTC
Hi,
this is a follow-up to a question posted on [neuroStarts](https://neurostars.org/t/derivativesdatasink-corrupting-files-and-bus-error/19266?u=fmorfini) where @effigies was helping me.

Briefly, I get a `Bus Error` when trying to get the output of a workflow in `NIFTI` instead of `NIFTI_GZ` using `DerivativesDatasink`. The Kernel from where I run my jupyter script dies, and only the first output is generated (but is damaged). I've unsuccessfully tried multiple plugins (`Linear`, `MultiProc`, and `SLURMGraph`) and alternative workflows (e.g. having `topup` outputs as NIFTI, or adding a `gunzip` node between topup and DS, or using `compress=False` in the DerivateivesDatasink node). 
If I add the gunzip node, then running the DS node corrupts both its output and the input (this being the gunzipped output).
If I work with the default formats ie .nii.gz there are no problems.

Specifically, I've reproduced this error using the first 3 subjects (sub-013, sub-014, sub-015) of the openNeuro dataset: [ds003469](https://openneuro.org/datasets/ds003469/versions/1.0.0).
I'm working in a SURM HPC cluster and I preload fsl 6.0 GPU enabled prior to starting jupyter/conda.

Here is the info: 
- [code and other inputs](https://github.com/nipreps/niworkflows/files/6510684/openNeuro_ds003469.zip)
- [nipype output and Bus error](https://github.com/nipreps/niworkflows/files/6510617/output_and_bus_error.txt)
- [environment info](https://github.com/nipreps/niworkflows/files/6510597/environment.txt)
- [directories_organization](https://github.com/nipreps/niworkflows/files/6510645/directories_organization.txt)

Let me know if I can give additional info! Thanks a lot for your help!
Francesca

**Comment by effigies** [comment] 2021-06-11 13:04
@fmorfini I have a suspicion that this will be fixed by #641. Are you able to reproduce this issue with `fmriprep-docker`?

**Comment by fmorfini** [comment] 2021-06-12 14:16
@effigies thanks! I run it on an HPC cluster so singularity would work better in my case. Would the changes in #641 be included if I build a singularity image from docker://poldracklab/fmriprep:latest ?

**Comment by effigies** [comment] 2021-06-12 14:20
I'll see about pushing a new tag.

**Comment by effigies** [comment] 2021-06-12 14:26
I've pushed a branch that, once built, should be pullable from: `docker://nipreps/fmriprep:deterministic_derivatives`

You can check https://hub.docker.com/r/nipreps/fmriprep/tags to see if it's uploaded yet.

**Comment by fmorfini** [comment] 2021-06-12 15:39
I just remembered that this example didn't come from running fmriprep. I set up a quick pipeline directly in nipype and importing DerivativesDataSink from niworkflows.interfaces.bids. So I'm not sure that I can reproduce it via the fmriprep image?

**Comment by effigies** [comment] 2021-06-12 20:35
Oh, then just try upgrading niworkflows to 1.3.4.

**Comment by fmorfini** [comment] 2021-06-13 16:23
Thanks! With niworkflow 1.3.4 and nipype 1.6.0 I now get this error

```210613-12:19:53,63 nipype.workflow DEBUG:
	 [MultiProc] Starting (n_procs=28, mem_gb=168.63, cwd=/work/swglab/data/BANDA_U01/tmp/openNeuro_ds003469/scripts)
210613-12:19:53,67 nipype.workflow DEBUG:
	 Creating flat graph for workflow: wf_topup_fmaps
210613-12:19:53,75 nipype.workflow DEBUG:
	 expanding workflow: wf_topup_fmaps
210613-12:19:53,78 nipype.workflow DEBUG:
	 processing node: wf_topup_fmaps.datasource
210613-12:19:53,80 nipype.workflow DEBUG:
	 processing node: wf_topup_fmaps.merge_epi
210613-12:19:53,82 nipype.workflow DEBUG:
	 processing node: wf_topup_fmaps.est_topup
210613-12:19:53,84 nipype.workflow DEBUG:
	 processing node: wf_topup_fmaps.ds_topup_fout2
210613-12:19:53,86 nipype.workflow DEBUG:
	 processing node: wf_topup_fmaps.ds_topup_fout1
210613-12:19:53,99 nipype.workflow DEBUG:
	 finished expanding workflow: wf_topup_fmaps
210613-12:19:53,101 nipype.workflow INFO:
	 Workflow wf_topup_fmaps settings: ['check', 'execution', 'logging', 'monitoring']
210613-12:19:53,106 nipype.workflow DEBUG:
	 PE: expanding iterables
210613-12:19:53,107 nipype.workflow DEBUG:
	 Detected iterable nodes [wf_topup_fmaps.datasource]
210613-12:19:53,109 nipype.workflow DEBUG:
	 Expanding the iterable node wf_topup_fmaps.datasource...
210613-12:19:53,110 nipype.workflow DEBUG:
	 node: wf_topup_fmaps.datasource iterables: {'ID': <function _standardize_iterables.<locals>.make_field_func.<locals>.<lambda> at 0x2af4cfe3ac10>}
210613-12:19:53,111 nipype.workflow DEBUG:
	 ('subnodes:', [wf_topup_fmaps.datasource, wf_topup_fmaps.merge_epi, wf_topup_fmaps.est_topup, wf_topup_fmaps.ds_topup_fout1, wf_topup_fmaps.ds_topup_fout2])
210613-12:19:53,116 nipype.workflow DEBUG:
	 [Node] datasource - setting input ID = sub-013
210613-12:19:53,118 nipype.workflow DEBUG:
	 Parameterization: paramstr=_ID_sub-013
210613-12:19:53,119 nipype.workflow DEBUG:
	 PE: expanding iterables ... done
210613-12:19:53,152 nipype.workflow DEBUG:
	 Performing depth first search
210613-12:19:53,166 nipype.workflow INFO:
	 Running in parallel.
210613-12:19:53,168 nipype.workflow DEBUG:
	 Progress: 5 jobs, 0/0/1 (done/running/ready), 0/5 (pending_tasks/waiting).
210613-12:19:53,169 nipype.workflow DEBUG:
	 Tasks currently running: 0. Pending: 0.
210613-12:19:53,171 nipype.workflow INFO:
	 [MultiProc] Running 0 tasks, and 1 jobs ready. Free memory (GB): 168.63/168.63, Free processors: 28/28.
210613-12:19:53,268 nipype.workflow DEBUG:
	 Allocating wf_topup_fmaps.datasource ID=0 (0.20GB, 1 threads). Free: 168.43GB, 27 threads.
210613-12:19:53,274 nipype.workflow DEBUG:
	 [Node] Hashes: [('ID', 'sub-013'), ('function_str', "def _dict_ds(in_dict, ID):\n    IntendedFor = in_dict[ID]['IntendedFor']\n    fmap_AP = in_dict[ID]['fmap_AP']\n    fmap_PA = in_dict[ID]['fmap_PA']\n    fmaps = [fmap_AP , fmap_PA]\n\n    return IntendedFor, fmaps\n"), ('in_dict', [('sub-013', [('IntendedFor', '/work/swglab/data/BANDA_U01/tmp/openNeuro_ds003469/rawdata/sub-013/func/sub-013_task-rest_bold.nii.gz'), ('fmap_AP', ('/work/swglab/data/BANDA_U01/tmp/openNeuro_ds003469/rawdata/sub-013/fmap/sub-013-fmap-sub-013_dir-P_epi.nii.gz', '5cc47e9e1f0784c08a0b27716ffd49f7')), ('fmap_PA', ('/work/swglab/data/BANDA_U01/tmp/openNeuro_ds003469/rawdata/sub-013/fmap/sub-013-fmap-sub-013_dir-A_epi.nii.gz', '64d6cb7feb060d83e1ee0de793fa748b'))])]), ('needed_outputs', ['IntendedFor', 'fmaps'])], 3084ca57f7307f2026d4d5c61625b2ea, /work/swglab/data/BANDA_U01/tmp/openNeuro_ds003469/working_files/wf_topup_fmaps/_ID_sub-013/datasource/_0x3084ca57f7307f2026d4d5c61625b2ea.json, ['/work/swglab/data/BANDA_U01/tmp/openNeuro_ds003469/working_files/wf_topup_fmaps/_ID_sub-013/datasource/_0x3084ca57f7307f2026d4d5c61625b2ea.json']
210613-12:19:53,276 nipype.workflow DEBUG:
	 [Node] Up-to-date cache found for "wf_topup_fmaps.datasource".
210613-12:19:53,278 nipype.workflow DEBUG:
	 Checking hash "wf_topup_fmaps.datasource" locally: cached=True, updated=True.
210613-12:19:53,280 nipype.workflow DEBUG:
	 Skipping cached node wf_topup_fmaps.datasource with ID 0.
210613-12:19:53,282 nipype.workflow INFO:
	 [Job 0] Cached (wf_topup_fmaps.datasource).
210613-12:19:55,172 nipype.workflow DEBUG:
	 Progress: 5 jobs, 1/0/1 (done/running/ready), 0/4 (pending_tasks/waiting).
210613-12:19:55,178 nipype.workflow DEBUG:
	 Tasks currently running: 0. Pending: 0.
210613-12:19:55,291 nipype.workflow DEBUG:
	 Allocating wf_topup_fmaps.merge_epi ID=1 (0.20GB, 1 threads). Free: 168.43GB, 27 threads.
210613-12:19:55,295 nipype.workflow DEBUG:
	 [Node] Setting 1 connected inputs of node "merge_epi" from 1 previous nodes.
210613-12:19:55,298 nipype.utils DEBUG:
	 Loading pkl: /work/swglab/data/BANDA_U01/tmp/openNeuro_ds003469/working_files/wf_topup_fmaps/_ID_sub-013/datasource/result_datasource.pklz
210613-12:19:55,302 nipype.workflow DEBUG:
	 Resolving paths in outputs loaded from results file.
210613-12:19:55,304 nipype.workflow DEBUG:
	 output: fmaps
210613-12:19:55,307 nipype.workflow DEBUG:
	 [Node] merge_epi - setting input in_files = ['/work/swglab/data/BANDA_U01/tmp/openNeuro_ds003469/rawdata/sub-013/fmap/sub-013-fmap-sub-013_dir-P_epi.nii.gz', '/work/swglab/data/BANDA_U01/tmp/openNeuro_ds003469/rawdata/sub-013/fmap/sub-013-fmap-sub-013_dir-A_epi.nii.gz']
210613-12:19:55,311 nipype.workflow DEBUG:
	 [Node] Hashes: [('dimension', 't'), ('in_files', [('/work/swglab/data/BANDA_U01/tmp/openNeuro_ds003469/rawdata/sub-013/fmap/sub-013-fmap-sub-013_dir-P_epi.nii.gz', '5cc47e9e1f0784c08a0b27716ffd49f7'), ('/work/swglab/data/BANDA_U01/tmp/openNeuro_ds003469/rawdata/sub-013/fmap/sub-013-fmap-sub-013_dir-A_epi.nii.gz', '64d6cb7feb060d83e1ee0de793fa748b')]), ('output_type', 'NIFTI_GZ'), ('needed_outputs', ['merged_file'])], 5a6b989e141d27a4bc3edbb14e1ff68e, /work/swglab/data/BANDA_U01/tmp/openNeuro_ds003469/working_files/wf_topup_fmaps/_ID_sub-013/merge_epi/_0x5a6b989e141d27a4bc3edbb14e1ff68e.json, ['/work/swglab/data/BANDA_U01/tmp/openNeuro_ds003469/working_files/wf_topup_fmaps/_ID_sub-013/merge_epi/_0x5a6b989e141d27a4bc3edbb14e1ff68e.json']
210613-12:19:55,313 nipype.workflow DEBUG:
	 [Node] Up-to-date cache found for "wf_topup_fmaps.merge_epi".
210613-12:19:55,316 nipype.workflow DEBUG:
	 Checking hash "wf_topup_fmaps.merge_epi" locally: cached=True, updated=True.
210613-12:19:55,318 nipype.workflow DEBUG:
	 Skipping cached node wf_topup_fmaps.merge_epi with ID 1.
210613-12:19:55,320 nipype.workflow INFO:
	 [Job 1] Cached (wf_topup_fmaps.merge_epi).
210613-12:19:57,174 nipype.workflow DEBUG:
	 Progress: 5 jobs, 2/0/1 (done/running/ready), 0/3 (pending_tasks/waiting).
210613-12:19:57,176 nipype.workflow DEBUG:
	 Tasks currently running: 0. Pending: 0.
210613-12:19:57,295 nipype.workflow DEBUG:
	 Allocating wf_topup_fmaps.est_topup ID=2 (0.20GB, 1 threads). Free: 168.43GB, 27 threads.
210613-12:19:57,299 nipype.workflow DEBUG:
	 [Node] Setting 1 connected inputs of node "est_topup" from 1 previous nodes.
210613-12:19:57,302 nipype.utils DEBUG:
	 Loading pkl: /work/swglab/data/BANDA_U01/tmp/openNeuro_ds003469/working_files/wf_topup_fmaps/_ID_sub-013/merge_epi/result_merge_epi.pklz
210613-12:19:57,306 nipype.workflow DEBUG:
	 Resolving paths in outputs loaded from results file.
210613-12:19:57,309 nipype.workflow DEBUG:
	 output: merged_file
210613-12:19:57,311 nipype.workflow DEBUG:
	 [Node] est_topup - setting input in_file = /work/swglab/data/BANDA_U01/tmp/openNeuro_ds003469/working_files/wf_topup_fmaps/_ID_sub-013/merge_epi/sub-013-fmap-sub-013_dir-P_epi_merged.nii.gz
210613-12:19:57,315 nipype.workflow DEBUG:
	 [Node] Hashes: [('config', 'b02b0.cnf'), ('encoding_file', ('/work/swglab/data/BANDA_U01/tmp/openNeuro_ds003469/derivatives/topup_fmaps_acqparams.txt', 'c45d2ac67285b56bab44e2179329290d')), ('fwhm', '6.0000000000'), ('in_file', ('/work/swglab/data/BANDA_U01/tmp/openNeuro_ds003469/working_files/wf_topup_fmaps/_ID_sub-013/merge_epi/sub-013-fmap-sub-013_dir-P_epi_merged.nii.gz', '9658b507356ac293261c896533bada3c')), ('out_jac_prefix', 'jac'), ('out_mat_prefix', 'xfm'), ('out_warp_prefix', 'warpfield'), ('output_type', 'NIFTI_GZ'), ('needed_outputs', ['out_field'])], 8c0f9499ffd1ce85130f186bde89413b, /work/swglab/data/BANDA_U01/tmp/openNeuro_ds003469/working_files/wf_topup_fmaps/_ID_sub-013/est_topup/_0x8c0f9499ffd1ce85130f186bde89413b.json, ['/work/swglab/data/BANDA_U01/tmp/openNeuro_ds003469/working_files/wf_topup_fmaps/_ID_sub-013/est_topup/_0x8c0f9499ffd1ce85130f186bde89413b.json']
210613-12:19:57,317 nipype.workflow DEBUG:
	 [Node] Up-to-date cache found for "wf_topup_fmaps.est_topup".
210613-12:19:57,320 nipype.workflow DEBUG:
	 Checking hash "wf_topup_fmaps.est_topup" locally: cached=True, updated=True.
210613-12:19:57,322 nipype.workflow DEBUG:
	 Skipping cached node wf_topup_fmaps.est_topup with ID 2.
210613-12:19:57,324 nipype.workflow INFO:
	 [Job 2] Cached (wf_topup_fmaps.est_topup).
210613-12:19:59,176 nipype.workflow DEBUG:
	 Progress: 5 jobs, 3/0/2 (done/running/ready), 0/2 (pending_tasks/waiting).
210613-12:19:59,182 nipype.workflow DEBUG:
	 Tasks currently running: 0. Pending: 0.
210613-12:19:59,185 nipype.workflow INFO:
	 [MultiProc] Running 0 tasks, and 2 jobs ready. Free memory (GB): 168.63/168.63, Free processors: 28/28.
210613-12:19:59,301 nipype.workflow DEBUG:
	 Allocating wf_topup_fmaps.ds_topup_fout2 ID=3 (0.20GB, 1 threads). Free: 168.43GB, 27 threads.
210613-12:19:59,306 nipype.workflow DEBUG:
	 [Node] Setting 2 connected inputs of node "ds_topup_fout2" from 2 previous nodes.
210613-12:19:59,308 nipype.utils DEBUG:
	 Loading pkl: /work/swglab/data/BANDA_U01/tmp/openNeuro_ds003469/working_files/wf_topup_fmaps/_ID_sub-013/datasource/result_datasource.pklz
210613-12:19:59,312 nipype.workflow DEBUG:
	 Resolving paths in outputs loaded from results file.
210613-12:19:59,315 nipype.workflow DEBUG:
	 output: IntendedFor
210613-12:19:59,317 nipype.workflow DEBUG:
	 [Node] ds_topup_fout2 - setting input source_file = /work/swglab/data/BANDA_U01/tmp/openNeuro_ds003469/rawdata/sub-013/func/sub-013_task-rest_bold.nii.gz
210613-12:19:59,320 nipype.utils DEBUG:
	 Loading pkl: /work/swglab/data/BANDA_U01/tmp/openNeuro_ds003469/working_files/wf_topup_fmaps/_ID_sub-013/est_topup/result_est_topup.pklz
210613-12:19:59,323 nipype.workflow DEBUG:
	 Resolving paths in outputs loaded from results file.
210613-12:19:59,326 nipype.workflow DEBUG:
	 output: out_field
210613-12:19:59,328 nipype.workflow DEBUG:
	 [Node] ds_topup_fout2 - setting input in_file = /work/swglab/data/BANDA_U01/tmp/openNeuro_ds003469/working_files/wf_topup_fmaps/_ID_sub-013/est_topup/sub-013-fmap-sub-013_dir-P_epi_merged_field.nii.gz
210613-12:19:59,332 nipype.workflow DEBUG:
	 [Node] Hashes: [('base_directory', '/work/swglab/data/BANDA_U01/tmp/openNeuro_ds003469/derivatives'), ('check_hdr', True), ('compress', [False]), ('in_file', [('/work/swglab/data/BANDA_U01/tmp/openNeuro_ds003469/working_files/wf_topup_fmaps/_ID_sub-013/est_topup/sub-013-fmap-sub-013_dir-P_epi_merged_field.nii.gz', '7993b2c5d81717f93d466f7ce372a8d1')]), ('source_file', ['/work/swglab/data/BANDA_U01/tmp/openNeuro_ds003469/rawdata/sub-013/func/sub-013_task-rest_bold.nii.gz']), ('suffix', 'topup_fmap2')], 7b8ed8832593364473f8461a8a5d7d81, /work/swglab/data/BANDA_U01/tmp/openNeuro_ds003469/working_files/wf_topup_fmaps/_ID_sub-013/ds_topup_fout2/_0x7b8ed8832593364473f8461a8a5d7d81.json, []
210613-12:19:59,334 nipype.workflow DEBUG:
	 [Node] No hashfiles found in "/work/swglab/data/BANDA_U01/tmp/openNeuro_ds003469/working_files/wf_topup_fmaps/_ID_sub-013/ds_topup_fout2".
210613-12:19:59,335 nipype.workflow DEBUG:
	 Checking hash "wf_topup_fmaps.ds_topup_fout2" locally: cached=False, updated=False.
210613-12:19:59,335 nipype.workflow DEBUG:
	 Running node wf_topup_fmaps.ds_topup_fout2 on master thread
210613-12:19:59,336 nipype.workflow INFO:
	 [Node] Setting-up "wf_topup_fmaps.ds_topup_fout2" in "/work/swglab/data/BANDA_U01/tmp/openNeuro_ds003469/working_files/wf_topup_fmaps/_ID_sub-013/ds_topup_fout2".
210613-12:19:59,342 nipype.workflow DEBUG:
	 [Node] Hashes: [('base_directory', '/work/swglab/data/BANDA_U01/tmp/openNeuro_ds003469/derivatives'), ('check_hdr', True), ('compress', [False]), ('in_file', [('/work/swglab/data/BANDA_U01/tmp/openNeuro_ds003469/working_files/wf_topup_fmaps/_ID_sub-013/est_topup/sub-013-fmap-sub-013_dir-P_epi_merged_field.nii.gz', '7993b2c5d81717f93d466f7ce372a8d1')]), ('source_file', ['/work/swglab/data/BANDA_U01/tmp/openNeuro_ds003469/rawdata/sub-013/func/sub-013_task-rest_bold.nii.gz']), ('suffix', 'topup_fmap2')], 7b8ed8832593364473f8461a8a5d7d81, /work/swglab/data/BANDA_U01/tmp/openNeuro_ds003469/working_files/wf_topup_fmaps/_ID_sub-013/ds_topup_fout2/_0x7b8ed8832593364473f8461a8a5d7d81.json, []
210613-12:19:59,343 nipype.workflow DEBUG:
	 [Node] No hashfiles found in "/work/swglab/data/BANDA_U01/tmp/openNeuro_ds003469/working_files/wf_topup_fmaps/_ID_sub-013/ds_topup_fout2".
210613-12:19:59,344 nipype.utils DEBUG:
	 Removing contents of /work/swglab/data/BANDA_U01/tmp/openNeuro_ds003469/working_files/wf_topup_fmaps/_ID_sub-013/ds_topup_fout2
210613-12:19:59,377 nipype.workflow DEBUG:
	 [Node] Writing pre-exec report to "/work/swglab/data/BANDA_U01/tmp/openNeuro_ds003469/working_files/wf_topup_fmaps/_ID_sub-013/ds_topup_fout2/_report/report.rst"
210613-12:19:59,405 nipype.workflow INFO:
	 [Node] Running "ds_topup_fout2" ("niworkflows.interfaces.bids.DerivativesDataSink")
210613-12:19:59,413 nipype.workflow DEBUG:
	 Saving results file: '/work/swglab/data/BANDA_U01/tmp/openNeuro_ds003469/working_files/wf_topup_fmaps/_ID_sub-013/ds_topup_fout2/result_ds_topup_fout2.pklz'
210613-12:19:59,414 nipype.workflow WARNING:
	 Storing result file without outputs
210613-12:19:59,427 nipype.workflow WARNING:
	 [Node] Error on "wf_topup_fmaps.ds_topup_fout2" (/work/swglab/data/BANDA_U01/tmp/openNeuro_ds003469/working_files/wf_topup_fmaps/_ID_sub-013/ds_topup_fout2)
210613-12:19:59,432 nipype.workflow DEBUG:
	 Clearing 3 from queue
210613-12:19:59,434 nipype.utils DEBUG:
	 Loading pkl: /work/swglab/data/BANDA_U01/tmp/openNeuro_ds003469/working_files/wf_topup_fmaps/_ID_sub-013/ds_topup_fout2/result_ds_topup_fout2.pklz
210613-12:19:59,436 nipype.workflow ERROR:
	 Node ds_topup_fout2.a0 failed to run on host d1003.
210613-12:19:59,437 nipype.workflow ERROR:
	 Saving crash info to /work/swglab/data/BANDA_U01/tmp/openNeuro_ds003469/scripts/crash-20210613-121959-f.morfini-ds_topup_fout2.a0-7a75fd1c-5f07-4084-bc03-c52ad7f0d934.pklz
Traceback (most recent call last):
  File "/home/f.morfini/softwares/miniconda3/envs/MRI/lib/python3.9/site-packages/nipype/pipeline/plugins/multiproc.py", line 344, in _send_procs_to_workers
    self.procs[jobid].run(updatehash=updatehash)
  File "/home/f.morfini/softwares/miniconda3/envs/MRI/lib/python3.9/site-packages/nipype/pipeline/engine/nodes.py", line 516, in run
    result = self._run_interface(execute=True)
  File "/home/f.morfini/softwares/miniconda3/envs/MRI/lib/python3.9/site-packages/nipype/pipeline/engine/nodes.py", line 635, in _run_interface
    return self._run_command(execute)
  File "/home/f.morfini/softwares/miniconda3/envs/MRI/lib/python3.9/site-packages/nipype/pipeline/engine/nodes.py", line 741, in _run_command
    result = self._interface.run(cwd=outdir)
  File "/home/f.morfini/softwares/miniconda3/envs/MRI/lib/python3.9/site-packages/nipype/interfaces/base/core.py", line 434, in run
    runtime = self._run_interface(runtime)
  File "/home/f.morfini/softwares/miniconda3/envs/MRI/lib/python3.9/site-packages/niworkflows/interfaces/bids.py", line 565, in _run_interface
    raise ValueError(f"Could not build path with entities {out_entities}.")
ValueError: Could not build path with entities {'subject': '013', 'task': 'rest', 'suffix': 'topup_fmap2', 'datatype': 'func', 'extension': 'nii'}.

210613-12:19:59,448 nipype.workflow INFO:
	 [Job 3] Completed (wf_topup_fmaps.ds_topup_fout2).
210613-12:19:59,532 nipype.workflow DEBUG:
	 Allocating wf_topup_fmaps.ds_topup_fout1 ID=4 (0.20GB, 1 threads). Free: 168.43GB, 27 threads.
210613-12:19:59,536 nipype.workflow DEBUG:
	 [Node] Setting 2 connected inputs of node "ds_topup_fout1" from 2 previous nodes.
210613-12:19:59,538 nipype.utils DEBUG:
	 Loading pkl: /work/swglab/data/BANDA_U01/tmp/openNeuro_ds003469/working_files/wf_topup_fmaps/_ID_sub-013/datasource/result_datasource.pklz
210613-12:19:59,541 nipype.workflow DEBUG:
	 Resolving paths in outputs loaded from results file.
210613-12:19:59,543 nipype.workflow DEBUG:
	 output: IntendedFor
210613-12:19:59,545 nipype.workflow DEBUG:
	 [Node] ds_topup_fout1 - setting input source_file = /work/swglab/data/BANDA_U01/tmp/openNeuro_ds003469/rawdata/sub-013/func/sub-013_task-rest_bold.nii.gz
210613-12:19:59,546 nipype.utils DEBUG:
	 Loading pkl: /work/swglab/data/BANDA_U01/tmp/openNeuro_ds003469/working_files/wf_topup_fmaps/_ID_sub-013/est_topup/result_est_topup.pklz
210613-12:19:59,549 nipype.workflow DEBUG:
	 Resolving paths in outputs loaded from results file.
210613-12:19:59,551 nipype.workflow DEBUG:
	 output: out_field
210613-12:19:59,552 nipype.workflow DEBUG:
	 [Node] ds_topup_fout1 - setting input in_file = /work/swglab/data/BANDA_U01/tmp/openNeuro_ds003469/working_files/wf_topup_fmaps/_ID_sub-013/est_topup/sub-013-fmap-sub-013_dir-P_epi_merged_field.nii.gz
210613-12:19:59,555 nipype.workflow DEBUG:
	 [Node] Hashes: [('base_directory', '/work/swglab/data/BANDA_U01/tmp/openNeuro_ds003469/derivatives'), ('check_hdr', True), ('compress', [False]), ('in_file', [('/work/swglab/data/BANDA_U01/tmp/openNeuro_ds003469/working_files/wf_topup_fmaps/_ID_sub-013/est_topup/sub-013-fmap-sub-013_dir-P_epi_merged_field.nii.gz', '7993b2c5d81717f93d466f7ce372a8d1')]), ('source_file', ['/work/swglab/data/BANDA_U01/tmp/openNeuro_ds003469/rawdata/sub-013/func/sub-013_task-rest_bold.nii.gz']), ('suffix', 'topup_fmap1')], 50ed697cb547997754154ef7eddeda23, /work/swglab/data/BANDA_U01/tmp/openNeuro_ds003469/working_files/wf_topup_fmaps/_ID_sub-013/ds_topup_fout1/_0x50ed697cb547997754154ef7eddeda23.json, []
210613-12:19:59,557 nipype.workflow DEBUG:
	 [Node] No hashfiles found in "/work/swglab/data/BANDA_U01/tmp/openNeuro_ds003469/working_files/wf_topup_fmaps/_ID_sub-013/ds_topup_fout1".
210613-12:19:59,558 nipype.workflow DEBUG:
	 Checking hash "wf_topup_fmaps.ds_topup_fout1" locally: cached=False, updated=False.
210613-12:19:59,560 nipype.workflow DEBUG:
	 Running node wf_topup_fmaps.ds_topup_fout1 on master thread
210613-12:19:59,562 nipype.workflow INFO:
	 [Node] Setting-up "wf_topup_fmaps.ds_topup_fout1" in "/work/swglab/data/BANDA_U01/tmp/openNeuro_ds003469/working_files/wf_topup_fmaps/_ID_sub-013/ds_topup_fout1".
210613-12:19:59,564 nipype.workflow DEBUG:
	 [Node] Hashes: [('base_directory', '/work/swglab/data/BANDA_U01/tmp/openNeuro_ds003469/derivatives'), ('check_hdr', True), ('compress', [False]), ('in_file', [('/work/swglab/data/BANDA_U01/tmp/openNeuro_ds003469/working_files/wf_topup_fmaps/_ID_sub-013/est_topup/sub-013-fmap-sub-013_dir-P_epi_merged_field.nii.gz', '7993b2c5d81717f93d466f7ce372a8d1')]), ('source_file', ['/work/swglab/data/BANDA_U01/tmp/openNeuro_ds003469/rawdata/sub-013/func/sub-013_task-rest_bold.nii.gz']), ('suffix', 'topup_fmap1')], 50ed697cb547997754154ef7eddeda23, /work/swglab/data/BANDA_U01/tmp/openNeuro_ds003469/working_files/wf_topup_fmaps/_ID_sub-013/ds_topup_fout1/_0x50ed697cb547997754154ef7eddeda23.json, []
210613-12:19:59,564 nipype.workflow DEBUG:
	 [Node] No hashfiles found in "/work/swglab/data/BANDA_U01/tmp/openNeuro_ds003469/working_files/wf_topup_fmaps/_ID_sub-013/ds_topup_fout1".
210613-12:19:59,566 nipype.utils DEBUG:
	 Removing contents of /work/swglab/data/BANDA_U01/tmp/openNeuro_ds003469/working_files/wf_topup_fmaps/_ID_sub-013/ds_topup_fout1
210613-12:19:59,600 nipype.workflow DEBUG:
	 [Node] Writing pre-exec report to "/work/swglab/data/BANDA_U01/tmp/openNeuro_ds003469/working_files/wf_topup_fmaps/_ID_sub-013/ds_topup_fout1/_report/report.rst"
210613-12:19:59,627 nipype.workflow INFO:
	 [Node] Running "ds_topup_fout1" ("niworkflows.interfaces.bids.DerivativesDataSink")
210613-12:19:59,634 nipype.workflow DEBUG:
	 Saving results file: '/work/swglab/data/BANDA_U01/tmp/openNeuro_ds003469/working_files/wf_topup_fmaps/_ID_sub-013/ds_topup_fout1/result_ds_topup_fout1.pklz'
210613-12:19:59,635 nipype.workflow WARNING:
	 Storing result file without outputs
210613-12:19:59,647 nipype.workflow WARNING:
	 [Node] Error on "wf_topup_fmaps.ds_topup_fout1" (/work/swglab/data/BANDA_U01/tmp/openNeuro_ds003469/working_files/wf_topup_fmaps/_ID_sub-013/ds_topup_fout1)
210613-12:19:59,652 nipype.workflow DEBUG:
	 Clearing 4 from queue
210613-12:19:59,654 nipype.utils DEBUG:
	 Loading pkl: /work/swglab/data/BANDA_U01/tmp/openNeuro_ds003469/working_files/wf_topup_fmaps/_ID_sub-013/ds_topup_fout1/result_ds_topup_fout1.pklz
210613-12:19:59,657 nipype.workflow ERROR:
	 Node ds_topup_fout1.a0 failed to run on host d1003.
210613-12:19:59,659 nipype.workflow ERROR:
	 Saving crash info to /work/swglab/data/BANDA_U01/tmp/openNeuro_ds003469/scripts/crash-20210613-121959-f.morfini-ds_topup_fout1.a0-0591406a-6a02-45e9-b5c9-417732c55f72.pklz
Traceback (most recent call last):
  File "/home/f.morfini/softwares/miniconda3/envs/MRI/lib/python3.9/site-packages/nipype/pipeline/plugins/multiproc.py", line 344, in _send_procs_to_workers
    self.procs[jobid].run(updatehash=updatehash)
  File "/home/f.morfini/softwares/miniconda3/envs/MRI/lib/python3.9/site-packages/nipype/pipeline/engine/nodes.py", line 516, in run
    result = self._run_interface(execute=True)
  File "/home/f.morfini/softwares/miniconda3/envs/MRI/lib/python3.9/site-packages/nipype/pipeline/engine/nodes.py", line 635, in _run_interface
    return self._run_command(execute)
  File "/home/f.morfini/softwares/miniconda3/envs/MRI/lib/python3.9/site-packages/nipype/pipeline/engine/nodes.py", line 741, in _run_command
    result = self._interface.run(cwd=outdir)
  File "/home/f.morfini/softwares/miniconda3/envs/MRI/lib/python3.9/site-packages/nipype/interfaces/base/core.py", line 434, in run
    runtime = self._run_interface(runtime)
  File "/home/f.morfini/softwares/miniconda3/envs/MRI/lib/python3.9/site-packages/niworkflows/interfaces/bids.py", line 565, in _run_interface
    raise ValueError(f"Could not build path with entities {out_entities}.")
ValueError: Could not build path with entities {'subject': '013', 'task': 'rest', 'suffix': 'topup_fmap1', 'datatype': 'func', 'extension': 'nii'}.

210613-12:19:59,670 nipype.workflow INFO:
	 [Job 4] Completed (wf_topup_fmaps.ds_topup_fout1).
<networkx.classes.digraph.DiGraph at 0x2af4d02375b0>```

**Comment by oesteban** [comment] 2021-06-14 20:57
For some reason, the filename is attempted to be set ``'suffix': 'topup_fmap1'``, which is not valid (thanks to that underscore). Not sure why this is happening though

**Comment by fmorfini** [comment] 2021-06-14 21:52
@oesteban the `topup_fmap1` is a string I'm introducing as I thought it was a customizable field. This is one of the 2 datasink nodes:
```
    # Datasink 1
    ds_topup_fout1 = Node(DerivativesDataSink(
        base_directory=str(outdir), 
        out_path_base = 'topup_fmaps',
        compress=False,
        suffix='topup_fmap1',
    ), name='ds_topup_fout1', run_without_submitting=True)

```
I'm rerunning it with `suffix=topup1` but for some reason, the cached info of the topup node can't be found - so it's rerunning the topup node again too. Is avoiding underscores the only thing I should keep in mind when using suffix?

**Comment by oesteban** [comment] 2021-06-14 22:10
suffix=topup1 won't work either because topup1 is not a valid suffix in
BIDS (nor the BIDS-Derivatives config in niworkflows)

**Comment by fmorfini** [comment] 2021-06-15 21:25
@oesteban ah great to know! Following [this example](https://github.com/poldracklab/ds003-post-fMRIPrep-analysis/blob/master/workflows.py) it seemed that `suffix` and `desc` could be customized strings (unless tstats, zstat, varcope, etc were at some point bids-compatible), but I guess both the example and the niworkflow version I was using were a little old. Anyways, I was able to fix this. Thanks so much for your help!

**Comment by effigies** [comment] 2021-06-22 12:08
Looks like this was resolved. Thanks for checking, and please let me know if there's still something to do!

**Closed by effigies** 2021-06-22 12:08 UTC
